### ISSUE TITLE
Could not build command

### ISSUE THREAD

**Issue by henry74** [matthewmpalen/karaberry#11]
@matthewmpalen Seeing this error when selecting songs.  When I use the start.sh script using the url it loads fine.  
```
./start.sh https://www.youtube.com/watch?v=ifCAfAzOBJM
Video codec omx-h264 width 1280 height 720 profile 77 fps 25.000000
Audio codec aac channels 2 samplerate 44100 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 1280x720@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.00 display:0 layer:0 alpha:255 aspectMode:0
Stopped at: 00:00:01
have a nice day ;)
```
I'm guessing something is wrong with the code itself.  Here's what I'm seeing in the terminal:

```
2017/04/26 10:32:50 5 Seconds Of Summer: Amnesia
2017/04/26 10:32:53 Playing 5 Seconds Of Summer: Amnesia (https://www.youtube.com/watch?v=0QA5RuYP22Y)
2017/04/26 10:32:53 Song 2: Could not build command
2017/04/26 10:32:53 Finished: 5 Seconds Of Summer: Amnesia
2017/04/26 10:50:55 Frozen: Let It Go (Idina Menzel)
2017/04/26 10:50:58 Playing Frozen: Let It Go (Idina Menzel) (https://www.youtube.com/watch?v=ifCAfAzOBJM)
2017/04/26 10:50:58 Song 372: Could not build command
2017/04/26 10:50:58 Finished: Frozen: Let It Go (Idina Menzel)
```
Some other useful information:
```
$youtube-dl --version
2017.04.26
$omxplayer --version
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Fri, 23 Sep 2016 00:56:49 +0000
        Version   : dfea8c9 [master]
        Repository: https://github.com/popcornmix/omxplayer.git
```
Thoughts?

**Comment by henry74** [comment]
So I did a bit of digging and it looks like the songs.csv file has a filename associated with certain songs, but I clearly don't have those files locally.   Is the songs.csv generated automatically based on your configuration?  I think the code should look for a file and if it doesn't find it, it should go look on youtube to stream it.  Thoughts?

**Comment by henry74** [comment]
Sorry for the conversation with myself, but just saw you can pass flags when running karaberry which should rebuild the song list and address the problem above.  Here's a few errors I ran into:
```bash
./karaberry --player=omxplayer --build=true
2017/04/26 15:07:44 Generating song list
2017/04/26 15:07:44 Cannot open broken song file: open /home/pi/Documents/karaberry/media/broken: no such file or directory
```
Fixed the missing directory problem then ran again:
```bash
mkdir media/broken
./karaberry --player=omxplayer --build=true
2017/04/26 15:08:02 Generating song list
2017/04/26 15:08:02 Bad format: broken
2017/04/26 15:08:02 Bad format: songs.csv
2017/04/26 15:08:02 Finished building song list
```
This removed everything from the songs.csv file...

**Comment by matthewmpalen** [comment]
Yes, I intended to fill in the docs at a convenient time. To be honest, I wasn't expecting someone else to try using the project. I can elaborate...

You can save local copies of the files using `youtube-dl` and putting them in the appropriate folder. Unfortunately, some of the Youtube videos are encoded in a way that are not compatible with `omxplayer`, but the majority should work fine. Those broken videos can be flagged separately so they won't appear in the UI -- otherwise it's annoying to see a song choice that will just exit immediately.

**Comment by matthewmpalen** [comment]
Also, the player will fallback to the streaming option if you don't have it saved locally.

**Comment by matthewmpalen** [comment]
I haven't used it recently, but I believe I also had a `youtube-dl` script that was crawling a karaoke playlist on Youtube to assemble `songs.csv` file that's included in the repo. On mine, I have I think most/all of those files saved locally. You might want to look into the `youtube-dl` documentation on how to do that.

**Comment by matthewmpalen** [comment]
I think it was something like this: https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-download-only-new-videos-from-a-playlist

**Comment by matthewmpalen** [comment]
Hope that makes sense. I'd say the first step would be to curate a list of some of the files you want to keep and download them using `youtube-dl`. If, when trying to play the local file, you get an `omxplayer` decoding error, you can add that to the `broken` file to force the program to stream that file instead. For some reason, streaming will work in those cases when local play will not :man_shrugging:

**Comment by henry74** [comment]
@matthewmpalen I made some code commits to my fork which do the following:

If filename is available, attempt to play song.  (unchanged)
If unable to find file in the media directory, try streaming instead (new)
In addition, download the file to the media directory (new)

Let me know if you want me to do a pull request.  

TODO: Allow adding new songs through the UI by providing a youtube URL
